curl 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyCA1pesf05VTg9ng2OZ-39wxxgYefQreAY' \
-H 'Content-Type: application/json' \
--data-binary '{"email":"test@test.com","password":"testtest","returnSecureToken":true}'